# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - refs/heads/internal-shade-testnet

resources:
  repositories:
  - repository: self

variables:
  imageRepositoryServiceName: 'securesecretstestnetconfig'
  containerRegistry: 'polarity-acr-svc-connect-09122022'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_Push_Service_custom
  displayName: Build_Push_Service_custom
  jobs:
  - job: Build_Push_Service_custom
    displayName: Build_Push_Service_custom
    condition: eq( variables['Build.SourceBranchName'], 'internal-shade-testnet' )
    steps:
    - checkout: self
      clean: true
    - bash: |
        export GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
    - task: Docker@2
      displayName: Build_Push_Service_custom
      inputs:
        containerRegistry: $(containerRegistry)
        repository:  $(imageRepositoryServiceName)
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.SourceBranchName)
          $(tag)
          $(Build.SourceVersion)
          $(GIT_COMMIT)

- stage: Build_Push_Service_pr
  displayName: Build_Push_Service_pr
  jobs:
  - job: Build_Push_Service_pr
    displayName: Build_Push_Service_pr
    condition: eq( variables['Build.Reason'], 'PullRequest' )
    steps:
    - checkout: self
      clean: true
    - bash: |
        export GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
    - task: Docker@2
      displayName: Build_Push_Service_pr
      inputs:
        containerRegistry: $(containerRegistry)
        repository:  $(imageRepositoryServiceName)
        command: 'buildAndPush'
        Dockerfile: 'node/Dockerfile'
        tags: |
          $(Build.SourceBranchName)
          $(tag)
          $(Build.SourceVersion)
          $(GIT_COMMIT)